services:
  db:
    container_name: epiceats-postgres
    image: postgres
    environment:
      POSTGRES_USER: epiceats
      POSTGRES_PASSWORD: password123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

volumes:
  db:

networks:
  db:
    driver: bridge


